### ISSUE TITLE
License

### ISSUE THREAD

**Issue by eerussianguy** [JDKDigital/treetap#1]
It's great to see new addons for TFC. I'd be happy to look over the mod, but noticed it's all rights reserved. The standard in our community is to use permissive licenses, to help make sure the code can continue to benefit and teach the community for years to come. It's common to use the very open MIT license, but authors who want more say over their code often use the LGPL license.

TFC itself is permissively licensed, and that's part of what's allowed this project to continue to exist on new versions. Specifically, we use the EUPL v1.2 license, which requires that derivative works be licensed under the same license as TFC. While we do not usually enforce this for addons, we do like to gently remind authors of ARR addons about this when it comes up.

**Comment by JaisDK** [comment]
This is technically not a TFC addon, it's a mod that has TFC compatibility and only a soft dependency on TFC for extra functionality. I do ARR for all my projects, not because I don't like sharing (I always keep the source visible), but because I don't want to deal with anyone having stupid ideas about what they can do with my code.
